version: 0.2
env:
  variables:
    TEST_ENV_VARIABLE: UserMicroService
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install boto3 -t ./
      - pip3 install bcrypt -t ./
      - pip3 install pycrypt -t ./
      - pip3 install flask -t ./
      - pip3 install pyjwt -t ./
  pre_build:
    commands:
      - python -m unittest -v tests/user_test.py
  build:
    commands:
      - export BUCKET=builds-user-module
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
  post_build:
    commands:
      - aws s3 sync swagger.yaml "s3://meetadoo-swagger"
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
  name: $Env:TEST_ENV_VARIABLE-$(Get-Date -UFormat "%Y%m%d-%H%M")
