version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip3 install boto3 -t ./
      - pip3 install bcrypt -t ./
      - pip3 install pycrypt -t ./
      - pip3 install unittest -t ./
      - pip3 install flask -t ./
      - export BUCKET=builds-user-module
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
