AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: User Module API Lambda
Resources:
  algo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.py
      Runtime: python3.7
      MemorySize: 256
      CodeUri: ./
      Events:
        RunEveryMinute:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
